### ISSUE TITLE
Workstation Beta — User Testing punchlist

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-ux#35]
In preparation for further user research to prepare the Beta build of the Workstation Client for Pilot Customer deployment, what are things we want to look at?

Please add or discuss things in the comments, here, and I'll update the below "Master List" accordingly.
---

- [ ] Files Checkout Flow
- [ ] Activity Messaging
- [ ] Sending messages to a Source
- [ ] Saving files from File Manager

**Comment by ninavizz** [comment]
Closing, as this was intended to guide development of Pilot user research plan.
