### ISSUE TITLE
Content: Contextual Help Panes

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-ux#61]
For the Beta Pilot release, we have [scoped-in an MVP contextual help solution](https://github.com/freedomofpress/securedrop-ux/issues/30#issuecomment-497044174) for the client. 

It will be a simple, non-scrollable non-modal pane that will simply have "close" buttons and written content on it, and nothing more. Below is a punchlist of all areas within the client that need content written to live on these panes. 

In the comments for this ticket, final drafts of this content will be entered w/ links to their Zeplin mockups & respective GitHub Client Repo issue. Please keep comments on task-tackling restricted to the above linked Issue for this design solution, or in the below Issues tackling each unique bit of functionality we're anticipating users will need guidance with. 

### Contextual Help content
- [ ] [Login](https://github.com/freedomofpress/securedrop-ux/issues/48) — ready to be drafted
  - Link-out text: `Trouble signing in?`
  - Speak to password & 2FA troubles
  - No visible link-out in Zeplin mox, as at that point this was out of scope. 
- [ ] [Export](https://github.com/freedomofpress/securedrop-ux/issues/57) — design drafted
  - Link-out text: `HELP` (across multiple panes, itemized below)
    - Pane: _Insert Drive_
    - Pane: _Decrypt_
    - Pane: _Save As_
- [ ] [Flag For Reply](https://github.com/freedomofpress/securedrop-ux/issues/46) — ready to be drafted
  - Link-out text: `Learn More` at end of blurb in the Reply pane's footprint from both the _Suspicious Activity_ and _Keypair Requested_ screens
    - Could be 2 separate content blurbs—one specific to each screen—or just one. Whichever solution is best.
  - Explaining the process in a little more detail than what's shown on the screen
- [ ] [Network Failure Resolution](https://github.com/freedomofpress/securedrop-ux/issues/32) — ready to be drafted
  - Link-out text: `Troubleshoot`
  - Basic whonix guidance
