### ISSUE TITLE
EPIC Ongoing Source UI things

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-ux#83]
_...creating this right now to track things. Cuz who doesn't like to track things?_

---

## Problem
After the 1.0 release has been pushed, the SecureDrop web experiences should continue to be iterated upon. Below is a list of known things to iterate upon, within today's _Source_ experience.

## Design Principles
- [From 1.0.0 release](https://invis.io/FYT9048HR7T)
- Going forward...
   - **Follow usability best practices**
     - Consistency, patterns; follow the knowledge.
  - **Prioritize Inclusion**
    - What might work for the widest swath of folks?
    - Written language, translations across languages, semiotics across cultures, color/contrast, legibility, a11y best practices
  - **Cultivate Calm**
     - Strive for page balance, not decoration.
     - Typography that prioritizes OS native-ubiquity (cough, Tor), legibility, and smooth reading to inform comprehension, in whichever `charset` the user will be choosing.
   - **Clear, human, humble, neutral**
      - Visually appealing, without calling attention to itself. 
      - SD is the messenger, not the message. Newsrooms are the carriers.
   - **Guide behavior to inform safe choices**
     - Design for known user needs and motivations, first.
     - Iterate and validate through testing: Written language choices, visual language choices, all contextually within the E2E experience journey.
      

## Yet to prioritize...
- [x] Update Languages widget (polish styling)
- [x] Move Codename widget to top of Submit page
- [x] Add TL;DR/LearnMore page
- [x] Update messaging styles
- [x] Update messaging content
- [x] Revisit "Confirmation" messaging
   - Per inability to do a proper `Active `state
- [x] Update "Reply" box styles
- [x] Revisit Tor messaging/ux
    - Design solution TBD
- [x] Update `body` and global typography things
   - More standardizing what's been done per-page in 1.0.0
- [x] Add Multi-file upload
- [x] ADMIN UI: Add section for news org name, and populate in Source UI

**Comment by ninavizz** [comment]
Closing, as items in [2021's SI Redesign](https://github.com/freedomofpress/securedrop/issues/6210), in-motion creation of a [Source Safety Guide](https://github.com/freedomofpress/securedrop/issues/6171), and overall team awareness of the need for multi-file uploads (also captured in [2019's SI UxR findings](https://docs.google.com/document/d/1YCpW8vNsu33tHB6_jDXrdlauC8y01AEbGX7h1PiKMsA/edit?usp=sharing)) meet each of the needs outlined in this issue.
